export const clientData = [
    {
        "id": "ABC123",
        "client_name": "Elite Gaming Lounge",
        "image": "https://randomuser.me/api/portraits/men/1.jpg",
        "game_station": "Elite Arcade",
        "incharge": "Michael Johnson",
        "contact": "+1-213-555-7890",
        "email": "michael.elite@example.com",
        "address": "789 Sunset Blvd, Suite 101",
        "location": "Los Angeles",
        "state": "California",
        "region": "Western",
        "commission_deal": "12% of total revenue",
        "commission_date": "2025-05-15",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 60000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Vendor Corp Ltd.",
        "no_of_game_machines": 18,
        "no_of_trts": 5,
        "no_of_branches": 3,
        "business_timings": { "weekdays": "10:00 AM - 11:00 PM", "weekends": "09:00 AM - 12:00 AM" },
        "games": [],
        "matches": []
    },
    {
        "id": "DEF456",
        "client_name": "Pixel Play Arena",
        "image": "https://randomuser.me/api/portraits/women/2.jpg",
        "game_station": "Pixel Station",
        "incharge": "Sarah Williams",
        "contact": "+1-415-555-1234",
        "email": "sarah.pixel@example.com",
        "address": "456 Market St, Floor 3",
        "location": "San Francisco",
        "state": "California",
        "region": "Western",
        "commission_deal": "10% of total revenue",
        "commission_date": "2025-04-20",
        "documents_submitted": ["Business License", "Tax ID"],
        "deposit_amount": 45000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "GameTech Inc.",
        "no_of_game_machines": 12,
        "no_of_trts": 3,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "GHI789",
        "client_name": "Neon Nexus",
        "image": "https://randomuser.me/api/portraits/men/3.jpg",
        "game_station": "Neon Arcade",
        "incharge": "Robert Chen",
        "contact": "+1-212-555-5678",
        "email": "robert.neon@example.com",
        "address": "123 Broadway, Unit 200",
        "location": "New York",
        "state": "New York",
        "region": "Eastern",
        "commission_deal": "15% of total revenue",
        "commission_date": "2025-06-10",
        "documents_submitted": ["Business License", "Insurance Certificate", "Lease Agreement"],
        "deposit_amount": 75000,
        "reporting_to": "Regional Manager - Ms. Parker",
        "appointed_by": "Entertainment Partners LLC",
        "no_of_game_machines": 25,
        "no_of_trts": 7,
        "no_of_branches": 2,
        "business_timings": { "weekdays": "12:00 PM - 12:00 AM", "weekends": "11:00 AM - 1:00 AM" },
        "games": [],
        "matches": []
    },
    {
        "id": "JKL012",
        "client_name": "Virtual Vortex",
        "image": "https://randomuser.me/api/portraits/women/4.jpg",
        "game_station": "Vortex VR",
        "incharge": "Emily Rodriguez",
        "contact": "+1-305-555-9012",
        "email": "emily.vortex@example.com",
        "address": "789 Ocean Dr, Suite 50",
        "location": "Miami",
        "state": "Florida",
        "region": "Southern",
        "commission_deal": "8% of total revenue",
        "commission_date": "2025-03-30",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 35000,
        "reporting_to": "Regional Manager - Mr. Thompson",
        "appointed_by": "VR Experiences Inc.",
        "no_of_game_machines": 8,
        "no_of_trts": 2,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "1:00 PM - 11:00 PM", "weekends": "12:00 PM - 12:00 AM" },
        "games": [],
        "matches": []
    },
    {
        "id": "MNO345",
        "client_name": "Retro Reloaded",
        "image": "https://randomuser.me/api/portraits/men/5.jpg",
        "game_station": "Retro Station",
        "incharge": "David Kim",
        "contact": "+1-312-555-3456",
        "email": "david.retro@example.com",
        "address": "456 Michigan Ave, Level 2",
        "location": "Chicago",
        "state": "Illinois",
        "region": "Midwestern",
        "commission_deal": "13% of total revenue",
        "commission_date": "2025-07-22",
        "documents_submitted": ["Business License", "Tax ID", "Insurance Certificate"],
        "deposit_amount": 55000,
        "reporting_to": "Regional Manager - Ms. Lewis",
        "appointed_by": "Classic Games Co.",
        "no_of_game_machines": 15,
        "no_of_trts": 4,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "10:00 AM - 10:00 PM", "weekends": "9:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "PQR678",
        "client_name": "Cosmic Clash Zone",
        "image": "https://randomuser.me/api/portraits/women/6.jpg",
        "game_station": "Cosmic Arena",
        "incharge": "Jessica Wong",
        "contact": "+1-713-555-7890",
        "email": "jessica.cosmic@example.com",
        "address": "123 Main St, Plaza Level",
        "location": "Houston",
        "state": "Texas",
        "region": "Southern",
        "commission_deal": "11% of total revenue",
        "commission_date": "2025-05-05",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 48000,
        "reporting_to": "Regional Manager - Mr. Thompson",
        "appointed_by": "Galaxy Entertainment",
        "no_of_game_machines": 14,
        "no_of_trts": 3,
        "no_of_branches": 2,
        "business_timings": { "weekdays": "11:00 AM - 10:30 PM", "weekends": "10:00 AM - 11:30 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "STU901",
        "client_name": "Epic Esports Hub",
        "image": "https://randomuser.me/api/portraits/men/7.jpg",
        "game_station": "Epic Station",
        "incharge": "Daniel Brown",
        "contact": "+1-206-555-2345",
        "email": "daniel.epic@example.com",
        "address": "789 Pike St, Unit 300",
        "location": "Seattle",
        "state": "Washington",
        "region": "Western",
        "commission_deal": "14% of total revenue",
        "commission_date": "2025-08-18",
        "documents_submitted": ["Business License", "Tax ID", "Insurance Certificate", "Lease Agreement"],
        "deposit_amount": 65000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Esports Ventures LLC",
        "no_of_game_machines": 20,
        "no_of_trts": 6,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "12:00 PM - 11:00 PM", "weekends": "10:00 AM - 12:00 AM" },
        "games": [],
        "matches": []
    },
    {
        "id": "VWX234",
        "client_name": "Arcade Odyssey",
        "image": "https://randomuser.me/api/portraits/women/8.jpg",
        "game_station": "Odyssey Arcade",
        "incharge": "Lisa Patel",
        "contact": "+1-602-555-6789",
        "email": "lisa.odyssey@example.com",
        "address": "456 Central Ave, Suite 100",
        "location": "Phoenix",
        "state": "Arizona",
        "region": "Western",
        "commission_deal": "9% of total revenue",
        "commission_date": "2025-04-15",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 40000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Sunbelt Amusements",
        "no_of_game_machines": 10,
        "no_of_trts": 2,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "YZA567",
        "client_name": "Next Level Gaming",
        "image": "https://randomuser.me/api/portraits/men/9.jpg",
        "game_station": "Next Level Arcade",
        "incharge": "Kevin Garcia",
        "contact": "+1-215-555-3456",
        "email": "kevin.nextlevel@example.com",
        "address": "123 Chestnut St, Floor 4",
        "location": "Philadelphia",
        "state": "Pennsylvania",
        "region": "Eastern",
        "commission_deal": "12% of total revenue",
        "commission_date": "2025-06-30",
        "documents_submitted": ["Business License", "Tax ID", "Insurance Certificate"],
        "deposit_amount": 52000,
        "reporting_to": "Regional Manager - Ms. Parker",
        "appointed_by": "Urban Entertainment Group",
        "no_of_game_machines": 16,
        "no_of_trts": 4,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 11:00 PM", "weekends": "10:00 AM - 12:00 AM" },
        "games": [],
        "matches": []
    },
    {
        "id": "BCD890",
        "client_name": "Game Grid",
        "image": "https://randomuser.me/api/portraits/women/10.jpg",
        "game_station": "Grid Station",
        "incharge": "Amanda Lee",
        "contact": "+1-619-555-7890",
        "email": "amanda.grid@example.com",
        "address": "789 Harbor Dr, Unit 150",
        "location": "San Diego",
        "state": "California",
        "region": "Western",
        "commission_deal": "10% of total revenue",
        "commission_date": "2025-05-25",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 42000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Coastal Amusements Inc.",
        "no_of_game_machines": 12,
        "no_of_trts": 3,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "10:30 AM - 10:30 PM", "weekends": "10:00 AM - 11:30 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "EFG123",
        "client_name": "Digital Domain",
        "image": "https://randomuser.me/api/portraits/men/11.jpg",
        "game_station": "Digital Arcade",
        "incharge": "Brian Wilson",
        "contact": "+1-404-555-4567",
        "email": "brian.digital@example.com",
        "address": "123 Peachtree St, Suite 400",
        "location": "Atlanta",
        "state": "Georgia",
        "region": "Southern",
        "commission_deal": "11% of total revenue",
        "commission_date": "2025-07-15",
        "documents_submitted": ["Business License", "Tax ID"],
        "deposit_amount": 47000,
        "reporting_to": "Regional Manager - Mr. Thompson",
        "appointed_by": "Southern Gaming Co.",
        "no_of_game_machines": 13,
        "no_of_trts": 3,
        "no_of_branches": 2,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "HIJ456",
        "client_name": "VR Oasis",
        "image": "https://randomuser.me/api/portraits/women/12.jpg",
        "game_station": "Oasis VR",
        "incharge": "Nicole Martinez",
        "contact": "+1-702-555-6789",
        "email": "nicole.oasis@example.com",
        "address": "456 Las Vegas Blvd, Level 2",
        "location": "Las Vegas",
        "state": "Nevada",
        "region": "Western",
        "commission_deal": "15% of total revenue",
        "commission_date": "2025-09-10",
        "documents_submitted": ["Business License", "Gaming License", "Insurance Certificate"],
        "deposit_amount": 80000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Desert Entertainment LLC",
        "no_of_game_machines": 22,
        "no_of_trts": 6,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "10:00 AM - 2:00 AM", "weekends": "10:00 AM - 3:00 AM" },
        "games": [],
        "matches": []
    },
    {
        "id": "KLM789",
        "client_name": "Pixel Paradise",
        "image": "https://randomuser.me/api/portraits/men/13.jpg",
        "game_station": "Pixel Hub",
        "incharge": "Jason Taylor",
        "contact": "+1-617-555-3456",
        "email": "jason.pixel@example.com",
        "address": "789 Boylston St, Floor 3",
        "location": "Boston",
        "state": "Massachusetts",
        "region": "Eastern",
        "commission_deal": "12% of total revenue",
        "commission_date": "2025-06-05",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 53000,
        "reporting_to": "Regional Manager - Ms. Parker",
        "appointed_by": "New England Amusements",
        "no_of_game_machines": 14,
        "no_of_trts": 4,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:30 PM", "weekends": "10:00 AM - 11:30 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "NOP012",
        "client_name": "Game Galaxy",
        "image": "https://randomuser.me/api/portraits/women/14.jpg",
        "game_station": "Galaxy Arcade",
        "incharge": "Rachel Kim",
        "contact": "+1-303-555-7890",
        "email": "rachel.galaxy@example.com",
        "address": "123 16th St, Suite 200",
        "location": "Denver",
        "state": "Colorado",
        "region": "Western",
        "commission_deal": "10% of total revenue",
        "commission_date": "2025-05-10",
        "documents_submitted": ["Business License", "Tax ID", "Insurance Certificate"],
        "deposit_amount": 44000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Mountain Gaming Co.",
        "no_of_game_machines": 11,
        "no_of_trts": 3,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "QRS345",
        "client_name": "Retro Rewind",
        "image": "https://randomuser.me/api/portraits/men/15.jpg",
        "game_station": "Rewind Arcade",
        "incharge": "Mark Davis",
        "contact": "+1-503-555-2345",
        "email": "mark.rewind@example.com",
        "address": "456 Burnside St, Unit 100",
        "location": "Portland",
        "state": "Oregon",
        "region": "Western",
        "commission_deal": "9% of total revenue",
        "commission_date": "2025-04-25",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 38000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Pacific Play Systems",
        "no_of_game_machines": 9,
        "no_of_trts": 2,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "12:00 PM - 10:00 PM", "weekends": "11:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "TUV678",
        "client_name": "Fusion Gaming",
        "image": "https://randomuser.me/api/portraits/women/16.jpg",
        "game_station": "Fusion Arcade",
        "incharge": "Olivia Smith",
        "contact": "+1-214-555-6789",
        "email": "olivia.fusion@example.com",
        "address": "123 Main St, Suite 300",
        "location": "Dallas",
        "state": "Texas",
        "region": "Southern",
        "commission_deal": "12% of total revenue",
        "commission_date": "2025-07-05",
        "documents_submitted": ["Business License", "Tax ID", "Insurance Certificate"],
        "deposit_amount": 51000,
        "reporting_to": "Regional Manager - Mr. Thompson",
        "appointed_by": "Lone Star Entertainment",
        "no_of_game_machines": 15,
        "no_of_trts": 4,
        "no_of_branches": 2,
        "business_timings": { "weekdays": "11:00 AM - 10:30 PM", "weekends": "10:00 AM - 11:30 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "WXY901",
        "client_name": "Nova Gaming Center",
        "image": "https://randomuser.me/api/portraits/men/17.jpg",
        "game_station": "Nova Arcade",
        "incharge": "Eric Wilson",
        "contact": "+1-704-555-3456",
        "email": "eric.nova@example.com",
        "address": "789 Trade St, Floor 2",
        "location": "Charlotte",
        "state": "North Carolina",
        "region": "Eastern",
        "commission_deal": "11% of total revenue",
        "commission_date": "2025-08-05",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 46000,
        "reporting_to": "Regional Manager - Ms. Parker",
        "appointed_by": "Atlantic Amusements",
        "no_of_game_machines": 13,
        "no_of_trts": 3,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "YZA234",
        "client_name": "Infinite Play",
        "image": "https://randomuser.me/api/portraits/women/18.jpg",
        "game_station": "Infinite Arcade",
        "incharge": "Sophia Chen",
        "contact": "+1-602-555-9012",
        "email": "sophia.infinite@example.com",
        "address": "456 Central Ave, Suite 200",
        "location": "Phoenix",
        "state": "Arizona",
        "region": "Western",
        "commission_deal": "10% of total revenue",
        "commission_date": "2025-06-20",
        "documents_submitted": ["Business License", "Tax ID"],
        "deposit_amount": 43000,
        "reporting_to": "Regional Manager - Mr. Adams",
        "appointed_by": "Desert Gaming LLC",
        "no_of_game_machines": 12,
        "no_of_trts": 3,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "BCD567",
        "client_name": "Game On! Arena",
        "image": "https://randomuser.me/api/portraits/men/19.jpg",
        "game_station": "Game On Station",
        "incharge": "Thomas Anderson",
        "contact": "+1-317-555-6789",
        "email": "thomas.gameon@example.com",
        "address": "123 Meridian St, Suite 150",
        "location": "Indianapolis",
        "state": "Indiana",
        "region": "Midwestern",
        "commission_deal": "9% of total revenue",
        "commission_date": "2025-05-30",
        "documents_submitted": ["Business License", "Insurance Certificate"],
        "deposit_amount": 39000,
        "reporting_to": "Regional Manager - Ms. Lewis",
        "appointed_by": "Heartland Gaming Co.",
        "no_of_game_machines": 10,
        "no_of_trts": 2,
        "no_of_branches": 1,
        "business_timings": { "weekdays": "11:00 AM - 10:00 PM", "weekends": "10:00 AM - 11:00 PM" },
        "games": [],
        "matches": []
    },
    {
        "id": "EFG890",
        "client_name": "Virtual Victory",
        "image": "https://randomuser.me/api/portraits/women/20.jpg",
        "game_station": "Victory VR",
        "incharge": "Jennifer Lopez",
        "contact": "+1-305-555-2345",
        "email": "jennifer.victory@example.com",
        "address": "789 Collins Ave, Unit 400",
        "location": "Miami",
        "state": "Florida",
        "region": "Southern",
        "commission_deal": "13% of total revenue",
        "commission_date": "2025-08-15",
        "documents_submitted": ["Business License", "Tax ID", "Insurance Certificate"],
        "deposit_amount": 54000,
        "reporting_to": "Regional Manager - Mr. Thompson",
        "appointed_by": "Sunshine Entertainment",
        "no_of_game_machines": 16,
        "no_of_trts": 4,
        "no_of_branches": 2,
        "business_timings": { "weekdays": "12:00 PM - 11:00 PM", "weekends": "11:00 AM - 12:00 AM" },
        "games": [],
        "matches": []
    }
];