
export const gameMachines = [
    {
        "machine_id": "M001",
        "machine_image": "https://example.com/machine1.jpg",
        "machine_model": "GS-2024",
        "features": ["HD Graphics", "Multiplayer", "VR Compatible"],
        "position": "Corner Section",
        "installed_location": "New York, NY",
        "installed_client_id": "C001",
        "installed_client_name": "GameZone Inc.",
        "region": "East Coast",
        "location_incharge": "Michael Scott",
        "installed_date": "2024-06-15",
        "serviced_on": "2025-02-10",
        "maintenance_date": "2025-04-01",
        "no_of_games": 50,
        "no_of_hours": 1200,
        "start_reading": 1000,
        "end_reading": 2200
    },
    {
        "machine_id": "M002",
        "machine_image": "https://example.com/machine2.jpg",
        "machine_model": "VRX-500",
        "features": ["4K Display", "Wireless Controllers", "Haptic Feedback"],
        "position": "Main Hall",
        "installed_location": "Los Angeles, CA",
        "installed_client_id": "C002",
        "installed_client_name": "FunHouse LLC",
        "region": "West Coast",
        "location_incharge": "Jim Halpert",
        "installed_date": "2023-12-20",
        "serviced_on": "2025-01-15",
        "maintenance_date": "2025-03-30",
        "no_of_games": 80,
        "no_of_hours": 1500,
        "start_reading": 2000,
        "end_reading": 3500
    },
    {
        "machine_id": "M003",
        "machine_image": "https://example.com/machine3.jpg",
        "machine_model": "A-007",
        "features": ["Classic Arcade", "Joystick Controls", "Coin Operated"],
        "position": "Near Entrance",
        "installed_location": "Chicago, IL",
        "installed_client_id": "C003",
        "installed_client_name": "Arcade Haven",
        "region": "Midwest",
        "location_incharge": "Pam Beesly",
        "installed_date": "2022-09-10",
        "serviced_on": "2024-12-05",
        "maintenance_date": "2025-06-10",
        "no_of_games": 30,
        "no_of_hours": 900,
        "start_reading": 500,
        "end_reading": 1400
    },
    {
        "machine_id": "M004",
        "machine_image": "https://example.com/machine4.jpg",
        "machine_model": "GTX-3090",
        "features": ["High FPS", "Esports Ready", "RGB Lighting"],
        "position": "VIP Section",
        "installed_location": "Houston, TX",
        "installed_client_id": "C004",
        "installed_client_name": "GameWorld",
        "region": "South",
        "location_incharge": "Dwight Schrute",
        "installed_date": "2024-02-18",
        "serviced_on": "2025-02-01",
        "maintenance_date": "2025-05-20",
        "no_of_games": 100,
        "no_of_hours": 2000,
        "start_reading": 3000,
        "end_reading": 5000
    },
    {
        "machine_id": "M005",
        "machine_image": "https://example.com/machine5.jpg",
        "machine_model": "ESL-9000",
        "features": ["Tournament Mode", "Leaderboard Integration", "Streaming Support"],
        "position": "E-Sports Arena",
        "installed_location": "Miami, FL",
        "installed_client_id": "C005",
        "installed_client_name": "Ultimate Play",
        "region": "Southeast",
        "location_incharge": "Stanley Hudson",
        "installed_date": "2023-07-25",
        "serviced_on": "2025-03-10",
        "maintenance_date": "2025-07-01",
        "no_of_games": 60,
        "no_of_hours": 1600,
        "start_reading": 2500,
        "end_reading": 4100
    }
]
