export const gameRecords = [
    {
        "client_id": "C001",
        "client_name": "GameZone Inc.",
        "game_station": "PlayStation Arena",
        "location": "New York, NY",
        "region": "East Coast",
        "date": "2025-03-25",
        "time": "14:30",
        "receipt_no": "R-1001",
        "customer_id": "CU1001",
        "customer_name": "John Doe",
        "machine_no_name": "GS-2024",
        "customer_deposit": 100,
        "game_amount": 50,
        "no_of_hours": 90,
        "machine_start_reading": 1200,
        "machine_end_reading": 1290,
        "won_by": "John Doe",
        "game_profit": 50,
        "game_machine_id": "GM-001",
        "paid_to_customer": 150,
        "registered_by": "Emily Roberts"
    },
    {
        "client_id": "C002",
        "client_name": "FunHouse LLC",
        "game_station": "VR Game Hub",
        "location": "Los Angeles, CA",
        "region": "West Coast",
        "date": "2025-03-25",
        "time": "16:15",
        "receipt_no": "R-1002",
        "customer_id": "CU1002",
        "customer_name": "Alice Smith",
        "machine_no_name": "VRX-500",
        "customer_deposit": 200,
        "game_amount": 100,
        "no_of_hours": 120,
        "machine_start_reading": 500,
        "machine_end_reading": 620,
        "won_by": "Alice Smith",
        "game_profit": 100,
        "game_machine_id": "GM-002",
        "paid_to_customer": 300,
        "registered_by": "Michael Johnson"
    },
    {
        "client_id": "C003",
        "client_name": "Arcade Haven",
        "game_station": "Classic Arcade",
        "location": "Chicago, IL",
        "region": "Midwest",
        "date": "2025-03-25",
        "time": "12:00",
        "receipt_no": "R-1003",
        "customer_id": "CU1003",
        "customer_name": "Robert Brown",
        "machine_no_name": "A-007",
        "customer_deposit": 50,
        "game_amount": 20,
        "no_of_hours": 45,
        "machine_start_reading": 800,
        "machine_end_reading": 845,
        "won_by": "House",
        "game_profit": 30,
        "game_machine_id": "GM-003",
        "paid_to_customer": 20,
        "registered_by": "Sarah Thompson"
    },
    {
        "client_id": "C004",
        "client_name": "GameWorld",
        "game_station": "PC Gaming Hub",
        "location": "Houston, TX",
        "region": "South",
        "date": "2025-03-25",
        "time": "18:45",
        "receipt_no": "R-1004",
        "customer_id": "CU1004",
        "customer_name": "Emily Davis",
        "machine_no_name": "GTX-3090",
        "customer_deposit": 150,
        "game_amount": 75,
        "no_of_hours": 110,
        "machine_start_reading": 1500,
        "machine_end_reading": 1610,
        "won_by": "Emily Davis",
        "game_profit": 75,
        "game_machine_id": "GM-004",
        "paid_to_customer": 225,
        "registered_by": "Daniel Martinez"
    },
    {
        "client_id": "C005",
        "client_name": "Ultimate Play",
        "game_station": "E-Sports Lounge",
        "location": "Miami, FL",
        "region": "Southeast",
        "date": "2025-03-25",
        "time": "20:10",
        "receipt_no": "R-1005",
        "customer_id": "CU1005",
        "customer_name": "James Wilson",
        "machine_no_name": "ESL-9000",
        "customer_deposit": 120,
        "game_amount": 60,
        "no_of_hours": 75,
        "machine_start_reading": 2000,
        "machine_end_reading": 2075,
        "won_by": "House",
        "game_profit": 60,
        "game_machine_id": "GM-005",
        "paid_to_customer": 60,
        "registered_by": "Laura Anderson"
    }
]
