export const matchRecord = [
    {
        "match_id": "M001",
        "client_id": "C001",
        "client_name": "GameZone Inc.",
        "client_image": "https://randomuser.me/api/portraits/men/1.jpg",
        "region": "East Coast",
        "game_station": "New York Arcade",
        "date": "2025-03-20",
        "match_amount": 500,
        "customer_id": "CU001",
        "customer_name": "John Doe",
        "customer_deposit": 300,
        "client_deposit": 200,
        "machine_id": "GM001",
        "machine_name": "Fortune Spin",
        "won_by": "Customer",
        "profit_to_client": 150,
        "paid_to_customer": 350,
        "paid_by": "Emily Watson",
        "receipt_no": "RPT2025032001"
    },
    {
        "match_id": "M002",
        "client_id": "C002",
        "client_name": "FunHouse LLC",
        "client_image": "https://randomuser.me/api/portraits/men/2.jpg",
        "region": "West Coast",
        "game_station": "Los Angeles PlayZone",
        "date": "2025-03-21",
        "match_amount": 700,
        "customer_id": "CU002",
        "customer_name": "Alice Smith",
        "customer_deposit": 500,
        "client_deposit": 200,
        "machine_id": "GM002",
        "machine_name": "Jackpot Mania",
        "won_by": "Client",
        "profit_to_client": 400,
        "paid_to_customer": 300,
        "paid_by": "James Carter",
        "receipt_no": "RPT2025032102"
    },
    {
        "match_id": "M003",
        "client_id": "C003",
        "client_name": "Arcade Haven",
        "client_image": "https://randomuser.me/api/portraits/women/3.jpg",
        "region": "Midwest",
        "game_station": "Chicago FunLand",
        "date": "2025-03-22",
        "match_amount": 600,
        "customer_id": "CU003",
        "customer_name": "Robert Brown",
        "customer_deposit": 400,
        "client_deposit": 200,
        "machine_id": "GM003",
        "machine_name": "Treasure Hunt",
        "won_by": "Customer",
        "profit_to_client": 200,
        "paid_to_customer": 400,
        "paid_by": "Sophia Miller",
        "receipt_no": "RPT2025032203"
    },
    {
        "match_id": "M004",
        "client_id": "C004",
        "client_name": "GameWorld",
        "client_image": "https://randomuser.me/api/portraits/men/4.jpg",
        "region": "South",
        "game_station": "Houston Gaming Arena",
        "date": "2025-03-23",
        "match_amount": 900,
        "customer_id": "CU004",
        "customer_name": "Daniel Wilson",
        "customer_deposit": 600,
        "client_deposit": 300,
        "machine_id": "GM004",
        "machine_name": "Mega Win",
        "won_by": "Client",
        "profit_to_client": 500,
        "paid_to_customer": 400,
        "paid_by": "Liam Johnson",
        "receipt_no": "RPT2025032304"
    },
    {
        "match_id": "M005",
        "client_id": "C005",
        "client_name": "Ultimate Play",
        "client_image": "https://randomuser.me/api/portraits/women/5.jpg",
        "region": "Southeast",
        "game_station": "Miami E-Sports Hub",
        "date": "2025-03-24",
        "match_amount": 800,
        "customer_id": "CU005",
        "customer_name": "Emily Davis",
        "customer_deposit": 500,
        "client_deposit": 300,
        "machine_id": "GM005",
        "machine_name": "Super Slots",
        "won_by": "Customer",
        "profit_to_client": 250,
        "paid_to_customer": 550,
        "paid_by": "Olivia Martin",
        "receipt_no": "RPT2025032405"
    }
];
