
export const paymentsData = [
    {
        "vendor_id": "VND001",
        "vendor_name": "Gaming Zone Inc.",
        "branch": "Las Vegas",
        "region": "West Coast",
        "date": "2025-03-27",
        "purpose_of_payment": "Purchases",
        "authorization_id": "AUTH1001",
        "authorization_name": "Michael Smith",
        "approved_by": "James Brown",
        "paid_amount": 15000,
        "paid_to": "Tech Supplies Ltd.",
        "receiver_id": "RCV5001",
        "receiver_name": "John Doe",
        "receiver_contact": "+1-702-555-1234",
        "purpose_description": "Payment for new arcade machine installations"
    },
    {
        "vendor_id": "VND002",
        "vendor_name": "Ultimate Fun Gaming",
        "branch": "Miami",
        "region": "East Coast",
        "date": "2025-03-27",
        "purpose_of_payment": "Client Commission",
        "authorization_id": "AUTH1002",
        "authorization_name": "Sophia Davis",
        "approved_by": "Robert Wilson",
        "paid_amount": 5000,
        "paid_to": "Client B Entertainment",
        "receiver_id": "RCV5002",
        "receiver_name": "Emily Brown",
        "receiver_contact": "+1-305-555-6789",
        "purpose_description": "Monthly commission payout for gaming revenue"
    },
    {
        "vendor_id": "VND003",
        "vendor_name": "Elite Gaming Solutions",
        "branch": "Houston",
        "region": "South",
        "date": "2025-03-27",
        "purpose_of_payment": "Machine Deposits",
        "authorization_id": "AUTH1003",
        "authorization_name": "David Johnson",
        "approved_by": "Sarah Lee",
        "paid_amount": 10000,
        "paid_to": "TRT Machine Services",
        "receiver_id": "RCV5003",
        "receiver_name": "Robert Wilson",
        "receiver_contact": "+1-713-555-2345",
        "purpose_description": "Deposit for new slot machines at Client C's arcade"
    },
    {
        "vendor_id": "VND004",
        "vendor_name": "Pro Gamer Hub",
        "branch": "Seattle",
        "region": "Northwest",
        "date": "2025-03-27",
        "purpose_of_payment": "Office Expenses",
        "authorization_id": "AUTH1004",
        "authorization_name": "Anna Roberts",
        "approved_by": "Mark Johnson",
        "paid_amount": 2500,
        "paid_to": "Office Supplies Co.",
        "receiver_id": "RCV5004",
        "receiver_name": "Sarah Adams",
        "receiver_contact": "+1-206-555-9876",
        "purpose_description": "Office furniture and maintenance costs"
    }
]
