
export const salaryAccounts = [
    {
        "vendor_id": "VND12345",
        "vendor_name": "Tech Solutions Inc.",
        "branch": "New York",
        "region": "East Coast",
        "emp_id": "EMP001",
        "emp_name": "John Doe",
        "designation": "Software Engineer",
        "department": "IT",
        "HOD": "Jane Smith",
        "working_days": 22,
        "amount_payable": 8000,
        "salary_advance": 500,
        "other_deductions": 200,
        "paid_amount": 7300,
        "payment_method": "Bank Transfer",
        "remarks": "Bonus Included",
        "pending_payment": 0,
        "date": "2025-03-27",
        "actions": ["View", "Edit", "Delete"]
    },
    {
        "vendor_id": "VND12346",
        "vendor_name": "Data Corp",
        "branch": "San Francisco",
        "region": "West Coast",
        "emp_id": "EMP002",
        "emp_name": "Emily Brown",
        "designation": "Data Analyst",
        "department": "Data Science",
        "HOD": "Michael Johnson",
        "working_days": 20,
        "amount_payable": 7500,
        "salary_advance": 1000,
        "other_deductions": 300,
        "paid_amount": 6200,
        "payment_method": "Check",
        "remarks": "Late Deduction Applied",
        "pending_payment": 0,
        "date": "2025-03-27",
        "actions": ["View", "Edit", "Delete"]
    },
    {
        "vendor_id": "VND12347",
        "vendor_name": "Finance Experts LLC",
        "branch": "Chicago",
        "region": "Midwest",
        "emp_id": "EMP003",
        "emp_name": "Robert Wilson",
        "designation": "Accountant",
        "department": "Finance",
        "HOD": "Sarah Lee",
        "working_days": 21,
        "amount_payable": 6800,
        "salary_advance": 700,
        "other_deductions": 150,
        "paid_amount": 5950,
        "payment_method": "Direct Deposit",
        "remarks": "Tax Adjustment Done",
        "pending_payment": 0,
        "date": "2025-03-27",
        "actions": ["View", "Edit", "Delete"]
    }
]
