export const blockedCustomers = [
    {
        "vendor_id": "VND001",
        "vendor_name": "Gaming Zone Inc.",
        "branch": "Las Vegas",
        "region": "West Coast",
        "client_id": "CLT1001",
        "client_name": "Arcade Paradise",
        "location": "Downtown Las Vegas",
        "customer_image": "https://randomuser.me/api/portraits/men/10.jpg",
        "customer_id": "CUST3001",
        "customer_name": "Ryan Cooper",
        "customer_contact": "+1-702-555-1111",
        "customer_address": "7890 Sunset Blvd, Las Vegas, NV",
        "customer_subscription": "Premium",
        "subscription_status": "Blocked",
        "customer_rating": 2.1,
        "no_of_visits": 12,
        "total_games_played": 80,
        "total_hours": 30,
        "total_games_amount": 1100,
        "won_avg": 20,
        "loss_avg": 80,
        "reward_points": 150,
        "block_reason": "Suspicious Activity"
    },
    {
        "vendor_id": "VND002",
        "vendor_name": "Game World LLC",
        "branch": "New York",
        "region": "East Coast",
        "client_id": "CLT2002",
        "client_name": "NYC Arcade Hub",
        "location": "Manhattan, NY",
        "customer_image": "https://randomuser.me/api/portraits/women/15.jpg",
        "customer_id": "CUST3002",
        "customer_name": "Sophia Martinez",
        "customer_contact": "+1-212-555-2222",
        "customer_address": "321 Park Ave, New York, NY",
        "customer_subscription": "Gold",
        "subscription_status": "Blocked",
        "customer_rating": 1.8,
        "no_of_visits": 8,
        "total_games_played": 50,
        "total_hours": 20,
        "total_games_amount": 800,
        "won_avg": 15,
        "loss_avg": 85,
        "reward_points": 80,
        "block_reason": "Violation of Terms"
    }
];
